version: '1.1'
services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  fullStoreApi:
    container_name: fullStoreApi
    image: node:16.14
    restart: always
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mysql
      - DB_NAME=fullStore
      - DB_USER=root
      - DB_PASSWORD=password
      - SERVER_PORT=3001
    volumes:
      - ./:/app
    working_dir: /app
    command: bash
    tty: true
    stdin_open: true
    depends_on:
      - mysql
